# Generated by Django 5.1.1 on 2024-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_cake',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='book_cake',
            name='Booking_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='book_cake',
            name='Cake_size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book_cake',
            name='Email_number',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='book_cake',
            name='Occassion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book_cake',
            name='Total_person',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='Item_name',
            field=models.CharField(max_length=40),
        ),
    ]
