# Generated by Django 5.1.1 on 2024-09-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_remove_book_cake_phone_number_book_cake_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('Rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='items',
            old_name='description',
            new_name='Description',
        ),
    ]
