# Generated by Django 5.1.1 on 2024-09-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_feedback_rename_description_items_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='description',
            new_name='Description',
        ),
    ]
